"""Beneficiaries model added

Revision ID: ee90fc357f08
Revises: 5d7d6620fe76
Create Date: 2024-07-16 03:58:03.333268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4abaa2843228'
down_revision = 'ee90fc357f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('beneficiaryName', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('beneficiaryAccountType', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('beneficiaryCountryCode', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('destinationCountry', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('destinationCurrency', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('payoutMethod', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('beneficiaryAccountNumber', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('routingCodeType1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('routingCodeValue1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiary')
    # ### end Alembic commands ###
