"""Items model extended for Nium's wallet data

Revision ID: a2643eaedd5c
Revises: 4abaa2843228
Create Date: 2024-07-16 16:48:28.201399

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a2643eaedd5c'
down_revision = '4abaa2843228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('walletHashId', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('item', sa.Column('regulatoryRegion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'regulatoryRegion')
    op.drop_column('item', 'status')
    op.drop_column('item', 'walletHashId')
    # ### end Alembic commands ###
