"""Beneficiaries model extended for beneficiaryHashId

Revision ID: c000f49f3d6a
Revises: a2643eaedd5c
Create Date: 2024-07-16 21:45:01.909597

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c000f49f3d6a'
down_revision = 'a2643eaedd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiary', sa.Column('beneficiaryHashId', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beneficiary', 'beneficiaryHashId')
    # ### end Alembic commands ###
